name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  AWS_DEBUG: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "ROLE_NAME=GitHubActionsRole" >> $GITHUB_ENV
          echo "ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV

      - name: Concatenate environment variables to create IAM Role ARN
        run: |
          ARN="arn:aws:iam::$ACCOUNT_ID:role/$ROLE_NAME-${REPO_NAME#*/}"
          echo "The IAM Role ARN is: $ARN"
          echo "ROLE_ARN=$ARN" >> $GITHUB_ENV
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: us-east-1 
      
      - name: Clear AWS Credentials Cache
        run: rm -rf ~/.aws/cli/cache
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Init Backend Bucket
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply Backend
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Destroy Terraform resources if anything goes wrong
        run: terraform destroy -auto-approve
        working-directory: ./terraform
        if: failure()  
